FROM node:20-alpine3.21
WORKDIR /opt/server
COPY package.json .
COPY package.js .
RUN npm install
ENV MONGO=true
ENV MONGO_URL=mongodb://mongodb:27017/catalogue
CMD ["npm", "start"]
FROM node:20-alpine3.21 AS builder
WORKDIR /opt/server
COPY package.json .
COPY *.js .
RUN npm install

